import { type Config } from "tailwindcss";
import {
  orangeDark,
  sandDark,
  greenDark,
  violetDark,
  yellowDark,
  tomatoDark,
  whiteA,
  blackA,
} from "@radix-ui/colors";

export const colors = {
  primary: {
    1: orangeDark.orange1,
    2: orangeDark.orange2,
    3: orangeDark.orange3,
    4: orangeDark.orange4,
    5: orangeDark.orange5,
    6: orangeDark.orange6,
    7: orangeDark.orange7,
    8: orangeDark.orange8,
    9: orangeDark.orange9,
    10: orangeDark.orange10,
    11: orangeDark.orange11,
    12: orangeDark.orange12,
  },

  neutral: {
    1: sandDark.sand1,
    2: sandDark.sand2,
    3: sandDark.sand3,
    4: sandDark.sand4,
    5: sandDark.sand5,
    6: sandDark.sand6,
    7: sandDark.sand7,
    8: sandDark.sand8,
    9: sandDark.sand9,
    10: sandDark.sand10,
    11: sandDark.sand11,
    12: sandDark.sand12,
  },

  success: {
    1: greenDark.green1,
    2: greenDark.green2,
    3: greenDark.green3,
    4: greenDark.green4,
    5: greenDark.green5,
    6: greenDark.green6,
    7: greenDark.green7,
    8: greenDark.green8,
    9: greenDark.green9,
    10: greenDark.green10,
    11: greenDark.green11,
    12: greenDark.green12,
  },

  secondary: {
    1: violetDark.violet1,
    2: violetDark.violet2,
    3: violetDark.violet3,
    4: violetDark.violet4,
    5: violetDark.violet5,
    6: violetDark.violet6,
    7: violetDark.violet7,
    8: violetDark.violet8,
    9: violetDark.violet9,
    10: violetDark.violet10,
    11: violetDark.violet11,
    12: violetDark.violet12,
  },

  warning: {
    1: yellowDark.yellow1,
    2: yellowDark.yellow2,
    3: yellowDark.yellow3,
    4: yellowDark.yellow4,
    5: yellowDark.yellow5,
    6: yellowDark.yellow6,
    7: yellowDark.yellow7,
    8: yellowDark.yellow8,
    9: yellowDark.yellow9,
    10: yellowDark.yellow10,
    11: yellowDark.yellow11,
    12: yellowDark.yellow12,
  },

  danger: {
    1: tomatoDark.tomato1,
    2: tomatoDark.tomato2,
    3: tomatoDark.tomato3,
    4: tomatoDark.tomato4,
    5: tomatoDark.tomato5,
    6: tomatoDark.tomato6,
    7: tomatoDark.tomato7,
    8: tomatoDark.tomato8,
    9: tomatoDark.tomato9,
    10: tomatoDark.tomato10,
    11: tomatoDark.tomato11,
    12: tomatoDark.tomato12,
  },

  white: {
    A1: whiteA.whiteA1,
    A2: whiteA.whiteA2,
    A3: whiteA.whiteA3,
    A4: whiteA.whiteA4,
    A5: whiteA.whiteA5,
    A6: whiteA.whiteA6,
    A7: whiteA.whiteA7,
    A8: whiteA.whiteA8,
    A9: whiteA.whiteA9,
    A10: whiteA.whiteA10,
    A11: whiteA.whiteA11,
    A12: whiteA.whiteA12,
  },

  black: {
    A1: blackA.blackA1,
    A2: blackA.blackA2,
    A3: blackA.blackA3,
    A4: blackA.blackA4,
    A5: blackA.blackA5,
    A6: blackA.blackA6,
    A7: blackA.blackA7,
    A8: blackA.blackA8,
    A9: blackA.blackA9,
    A10: blackA.blackA10,
    A11: blackA.blackA11,
    A12: blackA.blackA12,
  },
};

export default {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    colors,
    extend: {},
  },
  plugins: [],
} satisfies Config;
